export const site = {
  name: "Moroccan Court Kings",
  shortName: "MCK",
  tagline: "One court. One winner.",
  longTagline:
    "The first ever 1v1 basketball tournament in the African diaspora.",
  slogan: "Pure Passion.",
  email: "moroccancourtkings@gmail.com",
  instagram: "https://www.instagram.com/moroccancourtkings/",
  instagramHandle: "@moroccancourtkings",
  linkedin: "https://www.linkedin.com/in/moroccan-court-kings/",
  registerFormUrl: "https://tally.so/r/your-form-id",
  nav: [
    { href: "#about", label: "About" },
    { href: "#tournament", label: "Tournament" },
    { href: "#story", label: "Story" },
    { href: "#sponsors", label: "Sponsors" },
  ],
  champions: [
    {
      year: "",
      initials: "Abderrahamane",
      name: "Abderrahamane · @ahades_8",
      city: "Marrakech",
      caption: "First-ever 1v1 champion",
      photo: "/champions/champ1.png",
    },
    {
      year: "",
      initials: "Saad",
      name: "Saad · @sa3d_el08",
      city: "Marrakech",
      caption: "Ramadan Edition",
      photo: "/champions/champ2.jpg",
    },
    {
      year: "",
      initials: "Oussama",
      name: "Oussama · @usmv.bnvli",
      city: "Marrakech",
      caption: "Moroccan Mamba Edition",
      photo: "/champions/champMambaEdition.jpg",
    },
  ],
  sponsors: [
    {
      name: "Rchim",
      slug: "rchim",
      logo: "/logos/rchimLogo.png",
      role: "Streetwear Partner",
      description: "Marrakech-rooted streetwear, on every court we touch.",
      since: "2022",
      bannerBg: "#1A3A8E",
    },
    {
      name: "Drywich",
      slug: "drywich",
      logo: "/logos/drywichLogo.png",
      role: "Hospitality Partner",
      description: "Fueling the bracket, plate by plate, since day one.",
      since: "2022",
      bannerBg: "#2B1810",
    },
    {
      name: "Wear Basketball",
      slug: "wear-basketball",
      logo: "/logos/wearbasketballLogo.png",
      role: "Apparel Partner",
      description: "Hoop-first apparel, built for players who live the game.",
      since: "2022",
      bannerBg: "#163829",
    },
  ],
  aboutPhotos: [
    { src: "/photos/imgCarousel_1.JPG", caption: "In-game action" },
    { src: "/photos/imgCarousel_2.jpg", caption: "Court culture" },
    { src: "/photos/imgCarousel_3.png", caption: "Tournament day" },
    { src: "/photos/imgCarousel_4.png", caption: "First step on the line" },
    { src: "/photos/imgCarousel_9.png", caption: "Champion crowned" },
    { src: "/photos/imgCarousel_6.png", caption: "From the sidelines" },
    { src: "/photos/imgCarousel_7.png", caption: "Marrakech, sunset" },
    { src: "/photos/imgCarousel_8.png", caption: "From the sidelines" },
  ],
  tournamentFeatures: [
    {
      icon: "Swords",
      title: "1v1 Format",
      body: "Pure individual skill. One court, two players, one winner. No teammates to hide behind.",
    },
    {
      icon: "Trophy",
      title: "Bracket Play",
      body: "Open bracket, single-elimination. Win on the court, advance to the next round. No politics, just hoops.",
      comingSoon: true,
    },
    {
      icon: "Activity",
      title: "Live Scoring",
      body: "Real-time updates from courtside. Highlights captured by our in-house creators the moment they happen.",
      comingSoon: true,
    },
    {
      icon: "Medal",
      title: "Sponsor Drip",
      body: "Sponsor merch packs for the champion, gear for the finalists, recognition for the standout performers.",
    },
    {
      icon: "Users",
      title: "30+ Crew",
      body: "Creatives, sports managers, photographers, filmmakers. The full package, all in.",
    },
    {
      icon: "Globe",
      title: "Diaspora First",
      body: "The first ever 1v1 basketball tournament in the African diaspora. Marrakech tonight, the world next.",
    },
  ],
};
